### ISSUE TITLE
UnifiedDiffParserException on apparently sane file

### ISSUE THREAD

**Issue by moio** [java-diff-utils/java-diff-utils#104]
**Describe the bug**
`UnifiedDiffReader.parseUnifiedDiff` throws UnifiedDiffParserException on a patch which apparently looks good: 

https://git.stg.centos.org/rpms/adcli/blob/f29/f/0015-make-Samba-data-tool-configurable.patch

**To Reproduce**
Run this program: https://gist.github.com/moio/e6357cdd23d7645466c005004c4aa95c

(contains the literal patch as a string)

**Expected behavior**

No Exceptions.

**Actual behavior**

Dec 11, 2020 5:40:52 PM com.github.difflib.unifieddiff.UnifiedDiffReader processLine
WARNING:   >>> no rule matched diff --git a/library/adenroll.c b/library/adenroll.c
Exception in thread "main" com.github.difflib.unifieddiff.UnifiedDiffParserException: expected data line not found
	at com.github.difflib.unifieddiff.UnifiedDiffReader.parse(UnifiedDiffReader.java:104)
	at com.github.difflib.unifieddiff.UnifiedDiffReader.parseUnifiedDiff(UnifiedDiffReader.java:146)
	at Main.main(Main.java:303)
...

**System**
 - Java version: openjdk-11
 - Version: 4.9

**Suspect**

This `diff` line has a `--git` parameter which is not understood by the parser:

`diff --git a/configure.ac b/configure.ac`

**Notes**

:wave: java-diff-utils maintainers! Thanks for this library, it's helping me considerably! I am happy to test any PR to fix this.

**Comment by wumpz** [comment]
@moio Thx for using this library. I will look into your problem. 

May I introduce your patch file into this libraries tests?

**Comment by moio** [comment]
Sure! It comes from CentOS and it is LGPL IIUC. See the link above.

For the record, I'll be parsing some tens of thousands of patches from the Linux distro worlds, so that should be a pretty good test for the library :wink:!

**Comment by wumpz** [comment]
Cool. Since this new parser implementation is still very fresh I am happy that is already of help.

**Comment by wumpz** [comment]
I think I found the problem. It was not this **--git** parameter but this three numbered hunk before. The parser did not understand, how large this diff is and tried the next **diff** line as a data line, which is not valid and therefore throw this exception.

**Comment by wumpz** [comment]
```
diff --git a/doc/samba_data_tool_path.xml.in b/doc/samba_data_tool_path.xml.in
new file mode 100644
index 0000000..a667c57
--- /dev/null
+++ b/doc/samba_data_tool_path.xml.in

@@ -0,0 +1 @@   <--- this one

+@SAMBA_DATA_TOOL@
```

**Comment by wumpz** [comment]
I just deployed a new SNAPSHOT version 4.10-SNAPSHOT.

**Comment by moio** [comment]
Awesome, @wumpz, I just tested it and can confirm that the behavior is correct now!
