### ISSUE TITLE
GPLv3+ licensed files in the code base

### ISSUE THREAD

**Issue by D4N** [java-diff-utils/java-diff-utils#111]
The files [`java-diff-utils/src/test/resources/mocks/original.txt`](https://github.com/java-diff-utils/java-diff-utils/blob/master/java-diff-utils/src/test/resources/mocks/original.txt) and [`java-diff-utils/src/test/resources/mocks/revised.txt`](https://github.com/java-diff-utils/java-diff-utils/blob/master/java-diff-utils/src/test/resources/mocks/revised.txt) contain a GPLv3+ header. However, this project is licensed under the Apache 2.0 license. Is the license header in those two files outdated or is that intentional?

**Comment by wumpz** [comment]
I will replace those test files. So thx for pointing that out. I missed that.

**Comment by wumpz** [comment]
So that was not exactly the codebase but some test files this code tests work with.
