### ISSUE TITLE
Support for fuzzy patches

### ISSUE THREAD

**Issue by dpoetzsch** [java-diff-utils/java-diff-utils#112]
When generating a unified diff with context, I would like to be able to do a fuzzy apply of that patch. Does your library support this?

For example, take the following unified diff with context 3:

```
--- original
+++ modified
@@ -2,6 +2,9 @@
 2
 3
 4
+a
+b
+c
 5
 6
 7
```

And my file looks like the following (exactly the original but with three lines added to the top):

```
x
y
z
1
2
3
4
5
6
7
8
```

Using the linux `patch` tool I am still able to apply this patch:

```
$ patch -o - neworig udiff.patch
patching file - (read from neworig)
Hunk #1 succeeded at 5 with fuzz 1 (offset 3 lines).
```

When using `DiffUtils.patch` of your library I get an error (because the line numbers no longer match):

```
Incorrect Chunk: the chunk content doesn't match the target
```

Maybe there is a configuration option to enable fuzzy patching?

**Comment by wumpz** [comment]
How do those fuzzy patches work exactly? Are equal lines getting ignored?
Recently there was an option implemented to plugin behaviour on merge conflicts. But that is not what you want, right?

**Comment by dpoetzsch** [comment]
I think basically what the linux patch tool does, is to match by context instead of line numbers. So it looks for the nearest match with lines containing 2, 3, 4 followed by lines containing 5, 6, 7.

See https://www.gnu.org/software/diffutils/manual/html_node/Inexact.html

If you are interested I might try to port the implementation from gnu diffutils and create a PR if I find the time.

**Comment by wumpz** [comment]
Sure PRs are welcome. This behaviour should be optional.
