### ISSUE TITLE
changePosition NULL on UnifiedDiffReader.parseUnifiedDiff

### ISSUE THREAD

**Issue by elanzini** [java-diff-utils/java-diff-utils#117]
I was testing the tool and I picked a random commit from this repo to do so. Let's take https://github.com/java-diff-utils/java-diff-utils/commit/5338313a54c6eed065c3339a71870ba2d6fd0d0f. I accessed the `diff` of it by adding a `.diff` [at the end of the URL](https://github.com/java-diff-utils/java-diff-utils/commit/5338313a54c6eed065c3339a71870ba2d6fd0d0f.diff) and saved it into `diff.txt` file. I then used the tool to parse it in the following way:

``` java
public static void main(String[] args) throws IOException {
    var stream = new FileInputStream(new File("/path/to/diff.txt"));
    var patch  = UnifiedDiffReader.parseUnifiedDiff(stream);

    patch.getFiles().forEach(f -> {
        System.out.println("File: " + f.getFromFile());
        f.getPatch().getDeltas().forEach(delta -> {

            System.out.println("Source: ");
            System.out.println(delta.getSource().getPosition());
            delta.getSource().getChangePosition().forEach(System.out::print);

            System.out.println("Target: ");
            System.out.println(delta.getTarget().getPosition());
            delta.getTarget().getChangePosition().forEach(System.out::print);
        });
    });
}
```

The delta `getChangePosition` is just `null`. Am I doing something wrong?

**Comment by wumpz** [comment]
Indeed this is missing. It was added into the old parser while the new one was already in progress. I am on it.

**Comment by elanzini** [comment]
@wumpz any eta on when `4.10` will be released? looking forward to it!

**Comment by wumpz** [comment]
I will try it today evening.
-------- Ursprüngliche Nachricht --------Von: Edoardo Lanzini ***@***.***> Datum: 28.04.21  09:17  (GMT+01:00) An: java-diff-utils/java-diff-utils ***@***.***> Cc: Tobias ***@***.***>, Mention ***@***.***> Betreff: Re: [java-diff-utils/java-diff-utils] changePosition NULL on
  UnifiedDiffReader.parseUnifiedDiff (#117) 
@wumpz any eta on when 4.10 will be released? looking forward to it!

**Comment by wumpz** [comment]
Just released ... 
-------- Ursprüngliche Nachricht --------Von: Edoardo Lanzini ***@***.***> Datum: 28.04.21  09:17  (GMT+01:00) An: java-diff-utils/java-diff-utils ***@***.***> Cc: Tobias ***@***.***>, Mention ***@***.***> Betreff: Re: [java-diff-utils/java-diff-utils] changePosition NULL on
  UnifiedDiffReader.parseUnifiedDiff (#117) 
@wumpz any eta on when 4.10 will be released? looking forward to it!
