### ISSUE TITLE
Potential optimizations

### ISSUE THREAD

**Issue by Guillaume789** [java-diff-utils/java-diff-utils#126]
Hi,

I have moved from the initial Google diff project to this one as I prefer the package naming convention and the class refactoring.
Also thank you for maintaining this library.

The Myers’s algorithm is considered the best for Diff calculation, however it has complexity O(NR) and relies on matrices in order to evaluate all the possibilities.

**It is not adapted for large files and has performance issues.**

1)	A possible first improvement could be to reduce the size of the 2 input string, by removing the common sequence at the start and at the end.

**Example:**
Identify the initial common prefix:
       org.apache.commons.lang.StringUtils.getCommonPrefix(…)
Identify the final common prefix (reverse the string and get common prefix):
       org.apache.commons.lang.StringUtils.reverse(…)
       org.apache.commons.lang.StringUtils.getCommonPrefix(…)

Once the Delta are calculated, you could restore the initial and final Delta. (positions of existing Deltas need to be adjusted with the first common Delta)

2)	Another possible improvement could be to identify the longest common subsequence (ex: org.apache.commons.text.similarity.LongestCommonSubsequence) and to split the Strings according to this value.
Then calculate the Delta on the splitted strings and aggregate them at the end by adjusting the positions and also adding the common longest Delta.

Optimization 1 and 2 can be applied in the same time.

Many thanks,
Guillaume

Below an interesting post for potential improvements:
https://denisbider.blogspot.com/2019/11/a-better-sliding-matrix-diff-algorithm.html

**Comment by Guillaume789** [comment]
The above optimization will solve the performance issue reported by evgeny-pasynkov (post #124)

**Comment by Guillaume789** [comment]
Hi,
Below an example of code (not tested) to reduce the List<String> before processing it.
I could not test it as the setPosition() method is not visible.
Alternate solution is to create new Delta with adjusted position.


{code]
import java.util.List;

import com.github.difflib.patch.AbstractDelta;
import com.github.difflib.patch.Patch;

public class DiffUtils {

	/**
	 * Compute Patch
	 * @param source
	 * @param target
	 * @return
	 */
	public static Patch<String> diff(List<String> source, List<String> target) {
		int lcp = getIndexLCP(source, target);
		int lcs = getIndexLCS(source, target, lcp);
		
		List<String> sourceOpt = source.subList(lcp, lcs);
		List<String> targetOpt = target.subList(lcp, lcs);

		// Get patch
		Patch<String> patch = DiffUtils.diff(source, target);

		// get position start
		int indexStart = 0;
		for(int i=0;i<lcp;i++) {
			indexStart += source.get(i).length()+1;	// add +1 for EOL
		}
		
		// adjust positions
        for (AbstractDelta<String> delta : patch.getDeltas()) {
			int pos = delta.getSource().getPosition();
			// need method to set the position !!
//			delta.getSource().setPosition(pos+indexStart);		// No method !!!		
			//TODO: alternate solution is to create a new delta
		}
		
		return patch;
	}
	
	
	/**
	 * Get longest Common Prefix
	 * @param source
	 * @param target
	 * @return
	 */
	private static int getIndexLCP(List<String> source, List<String> target) {
		int i=0;
		while(i<source.size() && i<target.size()) {
			if(!source.get(i).equals(target.get(i))) {
				break;
			}
			i++;
		}
		return i;
	}

	/**
	 * Get longest Common Suffix
	 * @param source
	 * @param target
	 * @param lcp
	 * @return
	 */
	private static int getIndexLCS(List<String> source, List<String> target, int lcp) {
		int lcs = 0;
		int i=source.size()-1;
		int j=target.size()-1;
		int min = Math.max(0, lcp);
		
		while(i>=min && j>=min) {
			if(!source.get(i).equals(target.get(j))) {
				break;
			}
			i--;
			j--;
			lcs++;
		}
		return lcs;
	}

}
{code}

**Comment by Guillaume789** [comment]
According to my tests, this updated class gives worst performances !
I will continue my investigations...

**Comment by wumpz** [comment]
Looking into branch *introduce-optimized-meayers-al ...* you will find an optimized version of meyers which gives at least a 400 percent performance boost.

**Comment by cowwoc** [comment]
@wumpz When is the optimization going to get merged into master and released to Maven Central?

**Comment by wumpz** [comment]
Sorry for not informing you: [2b02951e8989eb74b132753feb21f1269cbfbf63. ](https://github.com/java-diff-utils/java-diff-utils/commit/2b02951e8989eb74b132753feb21f1269cbfbf63). Since github works well with those fixes and closes commit messages I guessed this merge would somehow link to your issue as well. My bet. 

So this change is already included in master and part of the latest snapshot. Look as well into the new factory for the default algorithm. There you could completly replace the algorithm that is used by default. However, I did not yet put this new algorithm in the default place, because the diff result will be different and there is a lot of code outthere that speculates on the "old" behaviour.


So could you check it?

**Comment by wumpz** [comment]
Looking into JGit it seems that for extreme diffs like 9000 lines to one line it will even not look into the diff itself but just construct a simple complete change (remove all, place one line). That gives at least in those cases a drastic performance gain.

**Comment by cowwoc** [comment]
@wumpz

> Looking into JGit it seems that for extreme diffs like 9000 lines to one line it will even not look into the diff itself but just construct a simple complete change (remove all, place one line). That gives at least in those cases a drastic performance gain.

That sounds bad to me. I would make this behavior configurable.

On a related note: I am diffing a String that is 600,000 characters long (the result of `Arrays.deepToString()` on a `float[][][]` and as you can imagine this is extremely slow. To make matters worse, I am breaking down the String into codepoints and feeding in `List<Integer>` so per the profiler the majority of the time is spent invoking `Integer.equals()`.

Out of the 600,000 characters, only a tiny minority has changed. I don't know how the diffing algorithm works but I am wondering if it would be quicker to diff two Strings of this length vs two `List<Integer>`. If this is true, I am wondering if it would be possible to divide the Strings into sub-sections, do a coarse-grained diff, then only do a codepoint comparison in sections that contain a difference. This might be quicker than invoking `Integer.equals()` hundreds of thousands of times.

Thoughts?
