### ISSUE TITLE
Markdown syntax not working in intellij

### ISSUE THREAD

**Issue by csj5483** [java-diff-utils/java-diff-utils#130]
DiffRowGenerator generator = DiffRowGenerator.create()
                    .showInlineDiffs(true)
                    .mergeOriginalRevised(true)
                    .inlineDiffByWord(true)
                    .oldTag(f -> "~")  
                    .newTag(f -> "**") **this is not making text bold**
                    .build();
            List<DiffRow> rows = generator.generateDiffRows(
                    Arrays.asList(resp.getBody().asString()),
                    Arrays.asList(map.get("JsonResponse").toString()));
            System.out.println(rows.get(0).getOldLine());

**Comment by wumpz** [comment]
This markdown syntax works for GitHub pages. So which dialect uses IntelliJ? You could simply replace it.

**Comment by wumpz** [comment]
Can we close this?
