### ISSUE TITLE
3-way merge

### ISSUE THREAD

**Issue by haodang** [java-diff-utils/java-diff-utils#132]
Hello there,

this looks a very useful library. Thank you for the nice work!

I was wondering if you were planning on add 3-way merge functionality with the generate patches?

**Comment by wumpz** [comment]
@haodang You mean something like: https://developpaper.com/principle-of-git-merge-recursive-three-way-merge-algorithm/.

Could you look into #32? This should provide the needed functionality. Could you test that?

**Comment by haodang** [comment]
@wumpz Thank you for your response! Please let me know if I didn't understand it correctly - the UnifiedDiff is just a different output format providing surrounding context as well as merge conflicts, but it didn't offer merge functionality, right?

I wrote a test as following, supposingly patch1 and patch2 are mergeable, but it ended with conflict.

Could you advise if this is supported?
```
    @Test
    public void test_merge() throws PatchFailedException {
        List<String> original = Arrays.asList("l1", "l2", "l3", "l4");
        List<String> revision1 = Arrays.asList("l1", "l2", "l3", "l3.5", "l4");
        List<String> revision2 = Arrays.asList("l1", "l2", "l3", "l4", "l5");
        final Patch<String> patch1 = DiffUtils.diff(
                original,
                revision1, true);
        System.out.println(patch1);

        final Patch<String> patch2 = DiffUtils.diff(
                original,
                revision2, true);
        System.out.println(patch2);

         // patch1 and patch2 are modifying different two parts of the same origin
         // they can be merged into l1 l2 l3 l3.5 l4 l5
        patch2.applyTo(revision1);
    }
```

**Comment by wumpz** [comment]
Aha. Understood. You mean fuzzy patches. I think there is an open PR. At the moment that applying does need exact line numbers, as you mentioned. With fuzzy patches only the context is scanned for similarity.
