### ISSUE TITLE
About unified diff format insert original file

### ISSUE THREAD

**Issue by 1506085843** [java-diff-utils/java-diff-utils#136]
If I get the unified diff format, I would like to know if there is a way to insert the unified diff format into the original file.
like this:
![image](https://user-images.githubusercontent.com/39946319/144576045-73f59c52-7f9b-45fd-b95c-c63c42164e9e.png)

In this way, I can easily parse this file through js or [diff2html
](https://github.com/rtfpessoa/diff2html) to form a beautiful comparison

**Comment by wumpz** [comment]
Not at the moment. But I think it should not be hard to implement. Since all Deltas are derived from AbstractDelta, I guess you should be able to replace the changes in the patch with classes that produce exactly your output.
