### ISSUE TITLE
Combining Patches

### ISSUE THREAD

**Issue by augustd** [java-diff-utils/java-diff-utils#139]
Would it be possible to combine patches using this library? For example, I have two (or multiple) unified diffs of the same set of files at different revisions. I want to load them each as `Patch` objects and then merge them together into a single unified diff, similar to the operation of [combinediff](https://linux.die.net/man/1/combinediff).

**Comment by wumpz** [comment]
Within Patch there is a method to generate a Patch from a list of changes.
