### ISSUE TITLE
Making it more efficient for comparing files

### ISSUE THREAD

**Issue by Thiluxan** [java-diff-utils/java-diff-utils#142]
The library is useful for the file comparison things, where we need to compare two files and need to find the differences between both files. I've used the Patch recently in one of my projects to generate differences between two contents from a file and was in a need to present it in a good looking UI. This case seems to be common use of this library and there are certain developments that can be made to support this kind of use case:

- For the comparison of multiple lines, the line numbers are array/list centric in the output, which starts at 0. There can be modifications to start from 1 if the user needs that kind of output.
- The output provided in the patch contains the strings separated and added into an array. Rather than that the output of each line can be provided as a single strength that is efficient from a UI perspective.

**Comment by wumpz** [comment]
Since arrays are at least in java always 0 based isn't the first point a simple change of output?

I don't get the second point of yours. What do you mean? That you can retrieve lines from a Patch instead of blocks?
