### ISSUE TITLE
Question: Is there a way to generate back raw Unified Diff from UnifiedDiff object?

### ISSUE THREAD

**Issue by challarao** [java-diff-utils/java-diff-utils#143]
I'm experimenting this library for one of my use cases. I have a git patch that I parse with #parseUnifiedDiff. Is there a way to get raw unified diff back from UnifiedDiff object? I see there is a generateUnifiedDiff method that requires original lines. 

My requirement is to try and get raw Unified Diff for each individual file from git patch. I can of course use the metadata from UnifiedDiff object and and hand code it myself. Just wondering if there is an existing way out of the lib.

This can be rephrased as splitting per file Unified Diff out of git patch.

**Comment by wumpz** [comment]
I am not quite sure if I understand you right. Isn't `UnifiedDiffWriterl.write` what you want? However, you are using the new implementation of this unified diff processing and the writer is not yet complete, so if you have problems lets improve it.

**Comment by martin-ncs** [comment]
Hey I'm dealing with a subset of this problem, I need to obtain a subset of a large diff

```java
UnifiedDiff diff = UnifiedDiffReader.parseUnifiedDiff(getStream());
UnifiedDiffFile file = select(diff);
String text = write(file) ??
```

Is this use case supported?
