### ISSUE TITLE
java-diff-utils 4.12 release ?

### ISSUE THREAD

**Issue by maartenc** [java-diff-utils/java-diff-utils#150]
Hi,

I would like to use the new fuzzy-patch logic from issue #112.
Any chance a new version could be released containing this functionality?

kind regards,
Maarten Coene

**Comment by wumpz** [comment]
sure, already on it :)

**Comment by maartenc** [comment]
Wow thanks ! 👍

**Comment by wumpz** [comment]
Thx for using java-diff-utils. :)
