### ISSUE TITLE
Applying patches with hunks followed by contents fails

### ISSUE THREAD

**Issue by DavideRossi** [java-diff-utils/java-diff-utils#156]
In short, java-diff-utils assumes that a hunk is a line on its own.
I'm parsing the output of `git log -p` that produces "inline" hunks like that:
`@@ -4,6 +4,9 @@ import com.github.javaparser.JavaParser;`
and that is not supported. I have no idea that format is OK with the unidiff specifications but the change to support that hunk format seems minimal.

**Comment by wumpz** [comment]
PRs are welcome. Please include a test.
