### ISSUE TITLE
Request: Include simple copy-paste snippets in README.md

### ISSUE THREAD

**Issue by reddaly** [java-diff-utils/java-diff-utils#158]
It requires significant digging to figure out how to use the library to generate a simple textual diff between two strings. I suggest adding a handful of example code snippets to the README.md file rather than directing readers to [the wiki](https://github.com/java-diff-utils/java-diff-utils/wiki), which itself redirects to the not particularly compelling [examples page](https://github.com/java-diff-utils/java-diff-utils/wiki/Examples).

The examples on [the examples page](https://github.com/java-diff-utils/java-diff-utils/wiki/Examples) would be more compelling if they included the input and outputs of the snippets.

**Comment by wumpz** [comment]
You know. Documentation is always tough. Do you have any suggestions? I thought pointing out the tests was ok.

**Comment by reddaly** [comment]
I think the key is to include a snippet and then show what happens when it
is executed.
https://github.com/java-diff-utils/java-diff-utils/wiki/Examples is pretty
close but is missing the execution for several examples.

I also think a lot of users don't care about deltas at all and just want a
diff they can print in a test. Showing a simple diff between two strings
might help people who just want that.

This is a reasonable example: https://gobyexample.com/if-else
