### ISSUE TITLE
Typo in classes Myers vs Meyers

### ISSUE THREAD

**Issue by sebkur** [java-diff-utils/java-diff-utils#159]
Looks like as part of the MyersDiff rewrite, the classes got renamed in https://github.com/java-diff-utils/java-diff-utils/commit/8bb4a9a8b1209f461b320a16150fc738107701ae from `Myers*` to `Meyers*` while the package is still `myers`. Looks like Myers is the correct spelling. Would you accept a pull request that renames the files and classes from Meyers to Myers?

**Comment by wumpz** [comment]
Seems you are right. I will correct it.

**Comment by sebkur** [comment]
thanks

**Comment by wumpz** [comment]
Thx for using java-diff-utils.
