### ISSUE TITLE
Color Android textview between ** and ~ 

### ISSUE THREAD

**Issue by developer-krushna** [java-diff-utils/java-diff-utils#162]
Sir can you help me...I want to color the specific text which is between ** and ~~ ... Is this possible with Android textview ?. thank you sir. It's a best project I ever seen..

**Comment by wumpz** [comment]
Thx. Could you be more specific, give a better example. However if you simply refer to the tags and how you could add some more markdown stuff you have to adapt the `oldTag`, `newTag` method calls. However this only works, if the Android textview supports some kind of css, html or markdown styling. So this should be sufficient regarding to (https://www.myandroidsolutions.com/2017/09/29/android-html-textview/#.Y-K2K3bMJaY). 

```java
DiffRowGenerator generator = DiffRowGenerator.create()
                .showInlineDiffs(true)
                .inlineDiffByWord(true)
                .oldTag(f -> "~")      //introduce markdown style for strikethrough
                .newTag(f -> "**")     //introduce markdown style for bold
                .build();
```

The `oldTag`, `newTag` methods are used to provide a Function<Boolean, String>. This function is called with `true` before the changed text and with `false` after it.  So this should do it:

```java
DiffRowGenerator generator = DiffRowGenerator.create()
                .showInlineDiffs(true)
                .inlineDiffByWord(true)
                .oldTag(f -> f?"<font color='red'>":"</font>")      //introduce markdown style for strikethrough
                .newTag(f -> f?"<font color='green'>":"</font>")     //introduce markdown style for bold
                .build();
```

**Comment by developer-krushna** [comment]
> Thx. Could you be more specific, give a better example. However if you simply refer to the tags and how you could add some more markdown stuff you have to adapt the `oldTag`, `newTag` method calls. However this only works, if the Android textview supports some kind of css, html or markdown styling. So this should be sufficient regarding to (https://www.myandroidsolutions.com/2017/09/29/android-html-textview/#.Y-K2K3bMJaY).
> 
> ```java
> DiffRowGenerator generator = DiffRowGenerator.create()
>                 .showInlineDiffs(true)
>                 .inlineDiffByWord(true)
>                 .oldTag(f -> "~")      //introduce markdown style for strikethrough
>                 .newTag(f -> "**")     //introduce markdown style for bold
>                 .build();
> ```
> 
> The `oldTag`, `newTag` methods are used to provide a Function<Boolean, String>. This function is called with `true` before the changed text and with `false` after it. So this should do it:
> 
> ```java
> DiffRowGenerator generator = DiffRowGenerator.create()
>                 .showInlineDiffs(true)
>                 .inlineDiffByWord(true)
>                 .oldTag(f -> f?"<font color='red'>":"</font>")      //introduce html style for strikethrough
>                 .newTag(f -> f?"<font color='green'>":"</font>")     //introduce html style for bold
>                 .build();
> ```

Thank you sir for your reply..I really very greatful  to you.. And it's working...
![Screenshot_2023-02-08-07-22-01-672](https://user-images.githubusercontent.com/76234660/217409952-8d22ab13-5837-4ca4-b166-3e8d5a8137ab.jpeg)


But one thing, Actually I am trying to make an app that can compare 2 text files.. But in my code 

DiffRowGenerator generator = DiffRowGenerator.create()
.showInlineDiffs(true)
.inlineDiffByWord(true)
.oldTag(f -> f?"<font color='red'>":"</font>")
.newTag(f -> f?"<font color='green'>":"</font>")
.build();
List<DiffRow> rows = generator.generateDiffRows(
Arrays.asList(FileUtil.readFile("/storage/emulated/0/Engine.java")),
Arrays.asList(FileUtil.readFile("/storage/emulated/0Engine (1).java")));
for (DiffRow row : rows) {
	textview1.setText(Html.fromHtml(row.getNewLine(), Html.FROM_HTML_MODE_COMPACT));
	textview2.setText(Html.fromHtml(row.getOldLine(), Html.FROM_HTML_MODE_COMPACT));
}



Here I defined all the requirements but I am confused, after text comparator why textview showing only the text line where the text is deleted or modified ... Just see my image , this portion is modified and it only showing the textview. not my other text ....How to solve it ..Thanks ❤️

**Comment by developer-krushna** [comment]
> Thx. Could you be more specific, give a better example. However if you simply refer to the tags and how you could add some more markdown stuff you have to adapt the `oldTag`, `newTag` method calls. However this only works, if the Android textview supports some kind of css, html or markdown styling. So this should be sufficient regarding to (https://www.myandroidsolutions.com/2017/09/29/android-html-textview/#.Y-K2K3bMJaY).
> 
> ```java
> DiffRowGenerator generator = DiffRowGenerator.create()
>                 .showInlineDiffs(true)
>                 .inlineDiffByWord(true)
>                 .oldTag(f -> "~")      //introduce markdown style for strikethrough
>                 .newTag(f -> "**")     //introduce markdown style for bold
>                 .build();
> ```
> 
> The `oldTag`, `newTag` methods are used to provide a Function<Boolean, String>. This function is called with `true` before the changed text and with `false` after it. So this should do it:
> 
> ```java
> DiffRowGenerator generator = DiffRowGenerator.create()
>                 .showInlineDiffs(true)
>                 .inlineDiffByWord(true)
>                 .oldTag(f -> f?"<font color='red'>":"</font>")      //introduce html style for strikethrough
>                 .newTag(f -> f?"<font color='green'>":"</font>")     //introduce html style for bold
>                 .build();
> ```

Thank you sir for your reply..I really very greatful  to you.. And it's working...
![Screenshot_2023-02-08-07-22-01-672](https://user-images.githubusercontent.com/76234660/217409952-8d22ab13-5837-4ca4-b166-3e8d5a8137ab.jpeg)


But one thing, Actually I am trying to make an app that can compare 2 text files.. But in my code 

DiffRowGenerator generator = DiffRowGenerator.create()
.showInlineDiffs(true)
.inlineDiffByWord(true)
.oldTag(f -> f?"<font color='red'>":"</font>")
.newTag(f -> f?"<font color='green'>":"</font>")
.build();
List<DiffRow> rows = generator.generateDiffRows(
Arrays.asList(FileUtil.readFile("/storage/emulated/0/Engine.java")),
Arrays.asList(FileUtil.readFile("/storage/emulated/0Engine (1).java")));
for (DiffRow row : rows) {
	textview1.setText(Html.fromHtml(row.getNewLine(), Html.FROM_HTML_MODE_COMPACT));
	textview2.setText(Html.fromHtml(row.getOldLine(), Html.FROM_HTML_MODE_COMPACT));
}



Here I defined all the requirements but I am confused, after text comparator why textview showing only the text line where the text is deleted or modified ... Just see my image , this portion is modified and it only showing the textview. not my other text ....How to solve it ..Thanks ❤️

**Comment by developer-krushna** [comment]
@wumpz 

Thank you sir for your reply..I really very greatful  to you.. And it's working...
![Screenshot_2023-02-08-07-22-01-672](https://user-images.githubusercontent.com/76234660/217409952-8d22ab13-5837-4ca4-b166-3e8d5a8137ab.jpeg)


But one thing, Actually I am trying to make an app that can compare 2 text files.. But in my code 

DiffRowGenerator generator = DiffRowGenerator.create()
.showInlineDiffs(true)
.inlineDiffByWord(true)
.oldTag(f -> f?"<font color='red'>":"</font>")
.newTag(f -> f?"<font color='green'>":"</font>")
.build();
List<DiffRow> rows = generator.generateDiffRows(
Arrays.asList(FileUtil.readFile("/storage/emulated/0/Engine.java")),
Arrays.asList(FileUtil.readFile("/storage/emulated/0Engine (1).java")));
for (DiffRow row : rows) {
	textview1.setText(Html.fromHtml(row.getNewLine(), Html.FROM_HTML_MODE_COMPACT));
	textview2.setText(Html.fromHtml(row.getOldLine(), Html.FROM_HTML_MODE_COMPACT));
}



Here I defined all the requirements but I am confused, after text comparator why textview showing only the text line where the text is deleted or modified ... Just see my image , this portion is modified and it only showing the textview. not my other text ....How to solve it ..Thanks ❤️

**Comment by wumpz** [comment]
`generator.reportLinesUnchanged(true)` delivers unchanged lines as well.

**Comment by developer-krushna** [comment]
@wumpz 

Sir giving same result..only one line even the if file have 3 line and 2nd and 3rd line have some text changes..but after text compare only showing the last line modification comparison

**Comment by wumpz** [comment]
You overwrite the previous line within your for loop. `setText` replaces text and does not append. So no problem with the diff tool.

**Comment by developer-krushna** [comment]
@wumpz  sir explain more clearly sir I unable to understand...Sir I am new 
> ```java

progressDialog = new ProgressDialog(MainActivity.this);
progressDialog.setMessage("Processing...");
progressDialog.show();
final Handler mHandler = new Handler() {
	public void handleMessage(Message msg) {
		progressDialog.dismiss();
	} 
};
new Thread() {
	public void run() {
		Looper.prepare();
		try {
			DiffRowGenerator generator = DiffRowGenerator.create()
			.showInlineDiffs(true)
			.inlineDiffByWord(true)
			.replaceOriginalLinefeedInChangesWithSpaces(false)
			.reportLinesUnchanged(true)
			.ignoreWhiteSpaces(false)
			.oldTag(f -> f?"<font color='red'>":"</font>")
			.newTag(f -> f?"<font color='green'>":"</font>")
			.build();
			List<DiffRow> rows = generator.generateDiffRows(
			Arrays.asList(textview1.getText().toString()),
			Arrays.asList(textview2.getText().toString()));
			for (DiffRow row : rows) {
				textview1.setText(textview1.getText().toString() + Html.fromHtml(row.getNewLine(), Html.FROM_HTML_MODE_COMPACT));
				textview2.setText(textview2.getText().toString() + Html.fromHtml(row.getOldLine(), Html.FROM_HTML_MODE_COMPACT));
			}
		} catch (Exception e) {
			SketchwareUtil.showMessage(getApplicationContext(), e.toString());
		}
		mHandler.sendEmptyMessage(0);
		Looper.loop();
	} }.start();
>


I have set a loop here but not working...
![Screenshot_2023-02-14-08-28-37-237](https://user-images.githubusercontent.com/76234660/218627727-95833761-7c9c-4dcd-8a8b-822d24838f48.jpeg)


Explain me with this code sir ....for which I can use it in my project thank you ♥️

**Comment by wumpz** [comment]
At first glance, you do not use your original `DiffRowGenerator` anymore. Why? It worked. Now you do not include any formatting tags into your found diffs 

```
.oldTag(f -> f?"":"")
.newTag(f -> f?"":"")
```

What does this do? Nothing. So nothing is hilited in your text.
