### ISSUE TITLE
Howto: Diff two objects and get the textual differences of its fields

### ISSUE THREAD

**Issue by philbannon** [java-diff-utils/java-diff-utils#165]
Hi All,

Just came across this tool and can I say its awesome. Thank you for building it. Now I know this isn't an issue but I was unable to find anywhere to ask a question for this repo.

So if it's allowed here's my question.

I have two Objects representing a users "Project", which is made up of the following:

```java
@Getter
@Setter
@Document(collection = "UserProjects")
public class Project {

    @JsonView({ProjectView.FullProjectView.class, ProjectView.FullProjectViewWithUserProfiles.class})
    @Id
    private String _id;

    private String blockId;

    private String userId;

    private String projectSlug;

    @NotBlank(message = "Project name is required")
    private String projectName;

    @NotBlank(message = "Project Body is required")
    private String projectBody;

    private String projectBodyPreview;

    private LinkedHashSet<CodeSnippet> codeSnippets;

    private String projectBodyPreviewPlain;

    private UserProfile projectCreator;
```

Now when a user updates / modifies the Project object I would like to be able to show a diff between whats changed and more importantly what fields changed. 

Looking at the documentation this is what I'm looking for on a per field level:

```java
        DiffRowGenerator generator = DiffRowGenerator.create()
                .showInlineDiffs(true)
                .mergeOriginalRevised(true)
                .inlineDiffByWord(true)
                .oldTag(f -> "~")      //introduce markdown style for strikethrough
                .newTag(f -> "**")     //introduce markdown style for bold
                .build();

        //compute the differences for two test texts.
        List<DiffRow> rows = new ArrayList<>();
                rows = (generator.generateDiffRows(
                Arrays.asList("This is a test senctence."),
                Arrays.asList("This is a test for diffutils.")));
```

And below might give an indication of what I'm hoping todo
```java
  try {
            Class clazz = project1.getClass();
            Field[] fields = clazz.getDeclaredFields();
            for (Field field : fields) {
                field.setAccessible(true);
                Object o1 = field.get(project1);
                Object o2 = field.get(project2);
                if (o1 == null && o2 == null) {
                    continue;
                } else if (o1 == null && o2 != null) {
                    diffRows.add(new DiffRow(DiffRow.Tag.INSERT, field.getName(), "", o2.toString()));
                } else if (o1 != null && o2 == null) {
                    diffRows.add(new DiffRow(DiffRow.Tag.DELETE, field.getName(), "", o1.toString(), ""));
                } else if (!o1.equals(o2)) {
                    diffRows.add(new DiffRow(DiffRow.Tag.CHANGE, field.getName(), "", o1.toString(), o2.toString()));
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
```

Can someone point me in the right direction please?

Thanks again

**Comment by wumpz** [comment]
So why do you use this library at all. You detect all the changes and now you only need to visualize those.

**Comment by 1506085843** [comment]
If your object only contains basic types or String types, then this is very easy, you can use reflection to get the values ​​of all member variables of the object for comparison. But if your object contains other complex objects nested, it is not easy to implement, such as Address in Student.java, Info in Address, just like LinkedHashSet<CodeSnippet>, UserProfile in your Project.java, you only Can deep clone your object, and then traverse each property for comparison

**Comment by wumpz** [comment]
But that is what you want and what java-diff-utils should do for you, a recursive scan and check for object properties. Right? So somewhere this nesting should be processed.
