### ISSUE TITLE
Requirement regarding conflict while applying a patch

### ISSUE THREAD

**Issue by BalaGanesa** [java-diff-utils/java-diff-utils#171]
Is there a way to resolve the conflict while applying a patch if not so could you please provide it.

**Comment by wumpz** [comment]
Using `Patch.withConflictOutput` you are able to process a *failed* patch.  At the moment there are two variants available:

* `Patch.CONFLICT_PRODUCES_EXCEPTION`: (default) throws an exception
* `Patch.CONFLICT_PRODUCES_MERGE_CONFLICT`: produces git like merge conflict texts within the target file

So you are able to solve the conflict manually at this point implementing your own conflict handler.
