### ISSUE TITLE
Add module-info.java to library

### ISSUE THREAD

**Issue by cowwoc** [java-diff-utils/java-diff-utils#172]
Please add `module-info.java` to this library. At first glance, the following content should do:

```
module io.github.javadiffutils
{
  exports com.github.difflib;
  exports com.github.difflib.patch;
}
```

**Comment by wumpz** [comment]
At the moment this project is build using Java 8. So I would not be able to build it including this module stuff.

**Comment by cowwoc** [comment]
@wumpz You can release a single JAR file that works for both Java 8 and newer versions of Java simultaneously.

See the `Add execution for Java 8` and `Add execution for Java 11` sections of https://medium.com/@ankitagrahari.rkgit/multi-release-functionality-8fc423b6c94e as an example, or more generally look up how `multiReleaseOutput` works.

**Comment by cowwoc** [comment]
This issue still exists.

**Comment by wumpz** [comment]
Sure but as mentioned above at the moment no module-info.java will be added. However using mavens jar plugin the automatic module name is set: 

```
 <Automatic-Module-Name>io.github.javadiffutils</Automatic-Module-Name>
```

**Comment by cowwoc** [comment]
@wumpz Did you read the part where I explained you could add `module-info.java` while maintaining JDK 8 support?

**Comment by wumpz** [comment]
@cowwoc I read it, but I am no fan of this multi version jars. If I upgrade to a higher Java version, this will definitly included, but not now.
