### ISSUE TITLE
this place will throw Exception

### ISSUE THREAD

**Issue by 90ji** [java-diff-utils/java-diff-utils#180]
https://github.com/java-diff-utils/java-diff-utils/blob/281c073c56a0cd0052963562e007c51ce2994983/java-diff-utils/src/main/java/com/github/difflib/patch/Chunk.java#L116

If the size of target is exactly 5

and fuzz =0  and  position = 5 

this place will throw exception

**Comment by wumpz** [comment]
You are right. What kind of behaviour do you propose?
