### ISSUE TITLE
Hanging on generateDiffRows

### ISSUE THREAD

**Issue by markwoon** [java-diff-utils/java-diff-utils#188]
The code:

```
    List<String> original = Files.readAllLines(oldFile);
    List<String> revised = Files.readAllLines(file);

    DiffRowGenerator generator = DiffRowGenerator.create()
        .showInlineDiffs(true)
        .mergeOriginalRevised(true)
        .inlineDiffByWord(true)
        .oldTag(f -> f ? "<s style=\"background-color: #bbbbbb\">" : "</s>")
        .newTag(f -> f ? "<b style=\"background-color: #aaffaa\">" : "</b>")
        .build();

    List<DiffRow> rows = generator.generateDiffRows(original, revised);
```

The files:  [test.zip](https://github.com/java-diff-utils/java-diff-utils/files/15240227/test.zip)

`generator.generateDiffRows` is hanging for me with these 2 files.

**System**
 - Java version: 17
 - java-diff-utils version: 4.12

**Comment by markwoon** [comment]
Still hoping for a fix.

**Comment by markwoon** [comment]
Still hoping for a fix.

**Comment by wumpz** [comment]
Sorry, that I was unavailable for so long.

I build a test around your data. May I introduce it into the project or are there any bits of non-publishable data in it?

One first remark. The difftools some time ago introduced a second diff algorithm: a variant of Myers algorithm with linear space usage which performs usually better for large datasets. You could try this one. Using the following snipped you introduce a different algorithm into the library:

```java
List<DiffRow> rows = generator.generateDiffRows(original, DiffUtils.diff(original, revised, new MyersDiffWithLinearSpace<String>() ));
``` 

Btw, you could set the default algorithm using `DiffUtils.withDefaultDiffAlgorithmFactory()`.

However, after digging around I was not able to do the diff with the original algorithm. The line normalizer and word splitter inflate the dataset so drastically, that it is not usable. The linear space algorithm generates other change sets.

**Comment by wumpz** [comment]
You should know the the linear space algorithm is not tested as deeply as the original implementation.

**Comment by markwoon** [comment]
Thanks for looking into this.

> I build a test around your data. May I introduce it into the project or are there any bits of non-publishable data in it?

Yes, go ahead.

I'll try your suggestion of the alternate algorithm the next time I return to that particular project, but sadly won't get to it any time soon.
