### ISSUE TITLE
Could we have a new official release? :)

### ISSUE THREAD

**Issue by MadnessIRL** [java-diff-utils/java-diff-utils#194]
The latest bug fixes were major, especially when evaluating diffs with gitlab.

Could we have an official release, or is perhaps possible for me to contribute in creating it? I would like avoiding maintaining my own in my private artifactory for long.

**Comment by wumpz** [comment]
Sorry. To late I know. 

There are some issues open, which I was not yet able to fix. PRs are welcome. However a release could be done if needed.

**Comment by MadnessIRL** [comment]
Never too late! Thank you for your reply. There will always be more issues :p Since our latest release is quite old, this would help a lot!

**Comment by wumpz** [comment]
starting next release (#196)

**Comment by wumpz** [comment]
Release is done. had some maven release problems. Therefore new version is 4.15.

**Comment by MadnessIRL** [comment]
Thank you so much you kind sir!
