### ISSUE TITLE
Support Hierarchy 

### ISSUE THREAD

**Issue by yairogen** [java-diff-utils/java-diff-utils#31]
### Expected Behavior
We need support for generating tree like diffs. Similar to a file system diff where you have folders compared as well as files.
In our case, we have groups of groups and we currently create separate diffs for each group. Having hierarchy support will enable us to create a single unified diff for the customer.

### Actual Behavior
Hierarchy not supported

### Specifications

  - Version: 4.0
  - Platform: Win/Linux
  - Subsystem:

**Comment by wumpz** [comment]
I am not quit sure what you have in mind? What should the diff tool do instead of comparing all groups one for each other? Could you give a concrete example?

**Comment by yairogen** [comment]
I am not sure how such a unified diff will be structured, but tools like BeyondCompare on windows know how to show you diffs between folders. This diff is showing which folders are different and drilling into those folders you see the files diff. 
So, I am looking for similar logic represented within one patch/diff file. 
Alas, I couldn't seem to find how such a hierarchy is expressed in a unified diff format. Was hoping you can assist with that.

**Comment by wumpz** [comment]
So is this within the tool you mentioned simply a presentation of multi diffs of files of folders? Or do you want to represent your groups as filenames? Make an example?

**Comment by yairogen** [comment]
![image](https://user-images.githubusercontent.com/4748515/53323526-0f7d9500-38e7-11e9-90e5-41195c349fc0.png)

**Comment by yairogen** [comment]
consider the attached zip
[diff.zip](https://github.com/java-diff-utils/java-diff-utils/files/2900408/diff.zip)
if I run:
`diff -bur one/ two/`
I get partially what I am looking for:
`--- one/bbb/hello3.txt
+++ two/bbb/hello3.txt
@@ -1 +1 @@
-first row
\ No newline at end of file
+second row
\ No newline at end of file
--- one/hello.txt
+++ two/hello.txt
@@ -1 +1 @@
-my name is Yoni
\ No newline at end of file
+my name is Yoni - What?
\ No newline at end of file`

It's partial because I am missing things like new files of folders on the right. however, it does give the a sort of hierarchy I am looking for.

what do you think?

**Comment by wumpz** [comment]
So I think I made the mistake to think you want to get a hierarchy from one Diff run. You want the UnifiedDiff builder to support it and if the diff runs multiple times in the background is not a problem, right?

**Comment by yairogen** [comment]
Not sure what you mean?
I think we need a way to generate one diff base on multiple patches. If the patches have a file like the hierarchy in their names it should be reflected in the unified diff output.

**Comment by wumpz** [comment]
I think we are talking about the same.

**Comment by yairogen** [comment]
great. thanks.
would you have time to get into it?

**Comment by wumpz** [comment]
I will look into it. Do you have a format description of unified diff format. All I found (wikipedia, gnu, ..) are not very clear, e.g. the header lines where the used diff command is stored. They all start with the +++ part.

**Comment by yairogen** [comment]
I'm afraid my sources are the same

**Comment by wumpz** [comment]
To support it the right way, the complete parser needs a rewrite to support the complete unified diff stuff, like add file, delete file.

**Comment by yairogen** [comment]
small chance I might be allowed to assist. if there are well defined tasks I can help with - please let me know/

**Comment by wumpz** [comment]
Started yesterday. I found a nearly complete project of a parser here at GitHub and will rewrite it in java. This would be a huge benefit for this library. That's why I want to go the whole way.

**Comment by wumpz** [comment]
So the parser seems to work, now I need the reverse, generate a UnifiedDiff from a patch. Sorry, for being a bit unavailable last time. If you are interessted I could push the branch, I implement it.

**Comment by yairogen** [comment]
I was moved to something else at work, but I'm sure I'll use this in the future - so please do push when ready.
Thanks a lot.

**Comment by wumpz** [comment]
The first version of it is merged into master. It passes the old tests, but is not yet feature complete.

**Comment by wumpz** [comment]
Any results here???

**Comment by yairogen** [comment]
@wumpz Sorry, as mentioned I am working on something else at the moment so wasn't able to test this out.

**Comment by wumpz** [comment]
Could you give me some test diffs, so I could I could more testcases?

**Comment by yairogen** [comment]
I don't have any. Sorry.

**Comment by alex-ponce** [comment]
Will this feature you are working on allow you to pass in 2 directories and produce a Unified diff of the contents? I'm looking for this functionality. Any idea when it could make it into a release?

**Comment by wumpz** [comment]
@alex-ponce That is the aim. However, I am still feature incomplete and need tests. E.g. unified diff supports file deletion and insertion, which is not yet implemented.

**Comment by wumpz** [comment]
@alex-ponce At the moment I look into it. Do you want to participate?

**Comment by wumpz** [comment]
No answer so far. I will close it.
