### ISSUE TITLE
How to do git-like conflict output

### ISSUE THREAD

**Issue by SevereOverfl0w** [java-diff-utils/java-diff-utils#32]
When git hits a conflict, instead of completely failing, it will create a file like so:

```
# Unchanged Line
<<<<<< HEAD
# their change
======
# our change
>>>>>>> my-branch
```

Could I produce something similar with this library?

I'm already using UnifiedDiff, but it only throws when encountering an issue.

**Comment by wumpz** [comment]
Not yet. UnifiedDiff parsing is rewritten at the moment.

**Comment by wumpz** [comment]
Just going to analyze this ...

**Comment by wumpz** [comment]
could you check this function like in `PatchTest.testPatch_Change_withExceptionProcessor`? Does this return the failed patch like you wanted it?
