### ISSUE TITLE
Unified patches from git do not parse correctly

### ISSUE THREAD

**Issue by nbransby** [java-diff-utils/java-diff-utils#33]
### Expected Behavior

Unified patches from git to parse correctly

### Actual Behavior

The git diffs contain extra context after the chunk header @@ suffix (I think its the closest line above the chunk with a '{') but the regex in the parser ends with @@$, expecting @@ to the last thing on the line

### Steps to Reproduce the Problem

  1. create a patch file with git diff 
  1. note the line in the chunk header
  1. attempt to parse with java-diff-utils

**Comment by wumpz** [comment]
I recently started to implement a complete unified diff parser. It is not yet ready but if you check the special unified diff branch if it parses your file correctly. 

I appreciate any feedback. The construction of a unified diff file is not yet implemented.

**Comment by nbransby** [comment]
Great! Will check it out

**Comment by wumpz** [comment]
The first version of it is merged into master. It passes the old tests, but is not yet feature complete.
