### ISSUE TITLE
It is possible to avoid the dependency on jgit?

### ISSUE THREAD

**Issue by nbransby** [java-diff-utils/java-diff-utils#34]
Its pulling it into my final jar even though I can see it is only used by jgit/HistogramDiff

**Comment by wumpz** [comment]
As long as you do not use HistogramDiff, you can safely exclude this dependency. Nevertheless it is a very fast implementation and very useful.

**Comment by wumpz** [comment]
Can we close this one?

**Comment by nbransby** [comment]
yes, this worked fine:

```groovy
                implementation("io.github.java-diff-utils:java-diff-utils:4.0") {
                    exclude group: 'org.eclipse.jgit', module: 'org.eclipse.jgit'
                }
```
