### ISSUE TITLE
DiffRowGenerator replaces < and >

### ISSUE THREAD

**Issue by JoJoDeveloping** [java-diff-utils/java-diff-utils#41]
### Expected Behavior
DiffRowGenerator would leave < and > the way they are
### Actual Behavior
DiffRowGenerator replaces < and > with their html entities. 
### Steps to Reproduce the Problem

  1. Run `DiffRowGenerator.create().generateDiffRows(List.of("<"), List.of("<"))`
  2. Observe that the resulting String has &amp;lt; instead of <

### Specifications

  - Version: 4.0
  - Platform: Linux
  - Subsystem: 

Using reportLinesUnchanged is not an option since that means tags are missing if an entire line is added/deleted. Having something like replaceSomeHTMLEntities with default true but optionally disableable would be nice, or being able to supply a general string normalisation function.

If needed/wanted I can PR this.

**Comment by wumpz** [comment]
I see. Let me think about a proper solution. Maybe it is time to provide a normalization hook into java-diff-utils. There the HTML entities are replaced in addition to tabs.

**Comment by wumpz** [comment]
I introduced the possibility to modify the used line normalizer. This should provide you with a tool to achieve what you want.

**Comment by codebusta** [comment]
Why this is not available in the maven repo, I'm using the following dependency:
        <dependency>
            <groupId>io.github.java-diff-utils</groupId>
            <artifactId>java-diff-utils</artifactId>
            <version>4.0</version>
        </dependency>

**Comment by wumpz** [comment]
The issue was closed after release 4.0 was created. You have to use 4.1-SNAPSHOT. The release is delayed due to the problematic new unified diff parser and writer. I don't want to put it into a release.

**Comment by codebusta** [comment]
Why this  4.1-SNAPSHOT is not available in maven repo to include in my project. What can you suggest?

**Comment by wumpz** [comment]
Hmm. Maybe I never deployed it?

**Comment by wumpz** [comment]
4.1-SNAPSHOT is deployed.

**Comment by wumpz** [comment]
Snapshots are deployed at sonatype.

**Comment by codebusta** [comment]
How I can include this snapshot in my pom.xml?

**Comment by codebusta** [comment]
Ok, found it, jfyi, include the following in your pom.xml:
>
     <profiles>
        <profile>
            <id>allow-snapshots</id>
            <activation><activeByDefault>true</activeByDefault></activation>
            <repositories>
                <repository>
                    <id>snapshots-repo</id>
                    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
                    <releases><enabled>false</enabled></releases>
                    <snapshots><enabled>true</enabled></snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>
