### ISSUE TITLE
Need to get raw text from DiffRow

### ISSUE THREAD

**Issue by rosta** [java-diff-utils/java-diff-utils#44]
### Code snippet
```java
	DiffRowGenerator generator = DiffRowGenerator.create()
			.showInlineDiffs(true)
			.mergeOriginalRevised(false)
			.inlineDiffByWord(true)
			.oldTag(f -> "~~")
			.newTag(f -> "**")
			.ignoreWhiteSpaces(true)
			.build();
	List<DiffRow> rows = generator.generateDiffRows(content1, content2);
	int line = 1;
	for (DiffRow row : rows) {
		if (isIncluded(row)) {
			// Write out the markdown ...
		}
		line++;
	}
```
The function `isIncluded()` is implemented as
```java
	private boolean isIncluded(DiffRow row) {
		if ( row.getTag() == Tag.EQUAL) {
			return false;
		}
		return excludePatterns.stream()
				.noneMatch(p -> p.matcher(row.getOldLine()).find()
						|| p.matcher(row.getNewLine()).find());
	}
````
where `excludePatterns` is a list of compiled regular expressions provided by the user.

### Challenge
The pattern is matched on the formatted lines, so the user has to provide regular expressions such as
    `  \* &lt;dt&gt;Generated&lt;/dt&gt;&lt;dd&gt;[0-9 :~*-]*&lt;/dd&gt;`
rather than 
    `  \* <dt>Generated</dt><dd>[0-9 :-]*</dt>`
which is more readable and less error prone.

In matter of fact the first regular expression doesn't work in any case because the markdown tag falls in the middle of the `</dd>` tag. For example:
> &amp;lt;dd&amp;gt;2019-07-&#42;&#42;26&#42;&#42; &#42;&#42;05:00&amp;lt;&#42;&#42;/dd&amp;gt;

NB I could have used the `reportLinesUnchanged(boolean)` builder config, but then I would lose the formatted lines which are used to output markdown code. (See the comment below as well)

### Request
Provide methods in the DiffRow
    `public String getRawOldLine()` 
and
    `public String getRawNewLine()`.

(By the way many thanks for this library, it's been very useful)

**Comment by rosta** [comment]
It appears that the configuration `reportLinesUnchanged` has no effect when `showInlineDiffs` is true. That is '<' and '>' characters are converted to HTML entities regardless.

**Comment by wumpz** [comment]
That is right. However, this option should be optional. It will double the needed memory of each line. 

I will look into it but do not have much time at the moment.

**Comment by rosta** [comment]
I agree completely that it should be optional.
