### ISSUE TITLE
multi-file diffs are not supported

### ISSUE THREAD

**Issue by uwesimm** [java-diff-utils/java-diff-utils#51]
(this is probably not a bug - its just missing)

the issue is that although a diff of multiple files are parsed but the patch information cannot be related back to which file they belong. At least I did not find an API to understand to which files a particular hunk/delta refers to. 

**To Reproduce**

'diff -U olddir newdir > udiff.diff' with some files differing

- now use UnifiedDiffUtils.parseUnifiedDiff("udiff.diff")

I would expect that it is possible now for every hunk to understand which fromFile and which toFile have been used to produce a particular delta/hunk.

**Comment by wumpz** [comment]
The implementation is pre alpha. A lot of stuff is missing. But if you could give me testdata or testcases it would be very helpful to go forward with it.
Writing this I see you are using the **old** method of parsing it (`UnifiedDiffUtils`). The new implementation is under` com.github.difflib.unifieddiff`. This is only available in the last snapshot.

**Comment by uwesimm** [comment]
```
mkdir old
mkdir new
echo "a\nb" > old/f1
echo "a\nc" > old/f2
echo "a\nb\nd" > new/f1
echo "a\nb\ndss" > new/f2
diff -U0 old new
```

**Comment by uwesimm** [comment]
results in
```
diff -U0 old/f1 new/f1
--- old/f1	2019-09-25 14:38:06.000000000 +0200
+++ new/f1	2019-09-25 14:38:27.000000000 +0200
@@ -1 +1 @@
-a\nb
+a\nb\nd
diff -U0 old/f2 new/f2
--- old/f2	2019-09-25 14:38:14.000000000 +0200
+++ new/f2	2019-09-25 14:38:32.000000000 +0200
@@ -1 +1 @@
-a\nc
```

**Comment by wumpz** [comment]
The latest additions should address this.

**Comment by wumpz** [comment]
I staged the first multi-module version at sonatype. There were no errors within my pom.xml after some editing. So wait and see, if this whole bunch is published to maven central. By the way, it should be version 4.4.
