### ISSUE TITLE
text/DiffRowGenerator customizing (custom algorithm, custom equalizer)

### ISSUE THREAD

**Issue by benoitpflieger** [java-diff-utils/java-diff-utils#52]
The DiffRowGenerator should be as customizable as the DiffUtils itself:
- algorithm
- equalizer

Moreover it would be helpfull to provide the type of Tag being processed by the tagGenerator.

**Comment by benoitpflieger** [comment]
Should you be interested, I could propose the code.

**Comment by wumpz** [comment]
The equalizer is set using the **ignoreWhitespace**. The algorithm itself is not yet settable.

I do not understand the second request to provide the type of Tag ...

**Comment by wumpz** [comment]
PRs are welcome. Propose your code so we have a better foundation to discuss this issue.

**Comment by wumpz** [comment]
@benoitpflieger   So any progress here?
