### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by dhendriks** [java-diff-utils/java-diff-utils#54]
Release 4.0 was released over 9 months ago, and there have been 72 commits to master since this release. Could we make a new release?

**Comment by wumpz** [comment]
What specific feature are you interested in? Imho the unified diff rewrite is not yet ready.

**Comment by wumpz** [comment]
Should I close this? Isn't there the need for a new release anymore?

**Comment by wumpz** [comment]
I staged the first multi-module version at sonatype. By the way, it should be version 4.4.

**Comment by dhendriks** [comment]
Thanks. Release 4.4 works for me.
