### ISSUE TITLE
[Feature request] Consider using gradle

### ISSUE THREAD

**Issue by dector** [java-diff-utils/java-diff-utils#56]
What do you think about using Gradle as a build system? It's [faster](https://gradle.org/gradle-vs-maven-performance/), don't require to embedded xml-parser chip into [your head](https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_using_standard_api) and has lots of [plugins](https://plugins.gradle.org/).

**Comment by dector** [comment]
Already done it [in my fork](https://github.com/java-diff-utils/java-diff-utils/compare/master...dector:dev-gradle). If you are interested - I can make PR here.

**Comment by wumpz** [comment]
Sorry, I am a maven guy, at least until now. I am using Netbeans as my IDE with super maven support. So for me no hurdle. My experiments with gradle took at least a similar way to: 

https://phauer.com/2018/moving-back-from-gradle-to-maven/

so I abadonded it.

**Comment by wumpz** [comment]
Do you think it is worth a try for this small project? At least the performance difference shouldn't be that noticeable.

**Comment by dector** [comment]
I guess it's not that important for a small project actually. :)

Probably, I'm just get used to Gradle and don't have too many problems with it (in general) and see/use it everywhere (but I'm not working in java enterprise world).

**Comment by dector** [comment]
Seems that Maven have [polyglot support](https://github.com/takari/polyglot-maven/) for configurations.
