### ISSUE TITLE
Problem with using 4.4 in modularized project (cannnot determine module name)

### ISSUE THREAD

**Issue by Siedlerchr** [java-diff-utils/java-diff-utils#60]
**Describe the bug**
Update to 4.4 in our JabRef (modularized application) fails. Gradle complains about the module name:
```
cannot determine module name for /home/travis/.gradle/caches/modules-2/files-2.1/io.github.java-diff-utils/java-diff-utils/4.4/87ebb16140d120da919b62117865954da06981b6/java-diff-utils-4.4.jar
/home/travis/build/JabRef/jabref/src/main/java/org/jabref/gui/mergeentries/DiffHighlighting.java:10: error: package com.github.difflib does not exist

import com.github.difflib.DiffUtils;
``` 

**To Reproduce**
Use the 4.4 in a modularized java project 
For reference, this is the PR which is failing: https://github.com/JabRef/jabref/pull/5594

I tried also to add the parent as well:
```
 compile 'io.github.java-diff-utils:java-diff-utils-parent:4.4'
  compile 'io.github.java-diff-utils:java-diff-utils:4.4'
```

**Expected behavior**
No errors

**System**
 - Java version 13
 - Version 4.4

**Comment by wumpz** [comment]
This is strange. I am using 

```
<dependency>
<groupId>io.github.java-diff-utils</groupId>
<artifactId>java-diff-utils</artifactId>
<version>4.4</version>
</dependency>
```

without any problems. Additionaly there is within the jars meta-inf the line:

**Automatic-Module-Name: io.github.java-diff-utils**

so nothing changed here. The module name is there.

Does gradle any additional checks, that are not mentioned in your error line?

**Comment by Siedlerchr** [comment]
It might be the fact that the Automatic Module Name is invalid. It contains dashes, which is not allowed:
https://sormuras.github.io/blog/2018-11-16-invalid-automatic-module-names.html
Checkced with 

`jar --describe-module --file <path to jar>`
>Automatic-Module-Name: io.github.java-diff-utils: Invalid module name: 'java-diff-utils' is not a Java identifier

**Comment by wumpz** [comment]
Hm. Strange. Version 4 contained the same module name and this version works for you, right?

**Comment by wumpz** [comment]
OK. At the moment I saw, that there was no module name in version 4.

**Comment by wumpz** [comment]
I confirm this as a bug. Somehow while modularizing the module name changed to this github groupid, which is indeed syntactically wrong. I will look into it.

**Comment by wumpz** [comment]
Could you check version 4.5-SNAPSHOT. I cleaned up the module name.

**Comment by Siedlerchr** [comment]
Can confirm works now in https://github.com/JabRef/jabref/pull/5620

**Comment by wumpz** [comment]
Ok. I will release v4.5 shortly.

**Comment by wumpz** [comment]
v4.5 released.
