### ISSUE TITLE
Whitespace visualization in diffs?

### ISSUE THREAD

**Issue by vlsi** [java-diff-utils/java-diff-utils#63]
Code formatting often involves "extra whitespace" or "missing whitespace" or "CRLF vs LF" issues.
Unfortunately, whitespace is not visible by default.

What if there was an option to visualize the whitespace that contributes to the diff?

For instance: use ␍␊ characters when output encoding allows. Use ·  for space visualization, and so on.

Note: the point is not "visualize all the whitespace characters", but "visualize only those chars that contribute to the diff".

**Comment by wumpz** [comment]
Since I have no clue what kind of (character) modifications someone could possibly think of, I will implement some kind of extension point.

**Comment by vlsi** [comment]
Oh,

By the way, I use ␍␊ in https://github.com/autostyle/autostyle, and it works great so far.

**Comment by vlsi** [comment]
Just in case, my experience with Windows console is it is extremely hard to output the proper characters.
That is, I just resort to `\n` and `\r` when running on Windows no matter what the default encoding is and so on :-/

**Comment by wumpz** [comment]
Now you could set a **processDiffs** function to process the diffed text to replace the text. Look at the corresponding test: `DiffRowGeneratorTest.testReplaceDiffsIssue63`.
