### ISSUE TITLE
ignoreBlankLines does not appear to be implemented

### ISSUE THREAD

**Issue by tilmans** [java-diff-utils/java-diff-utils#64]
**Describe the bug**
I'd like to remove blank lines from the diff generated by DiffRowGenerator but there's no option. I've had a look at the sources of the 4.5 release and I can see mention of this option there but no implementation or setter. WIP?

**System**
 - diffutils 4.5 from maven

**Comment by wumpz** [comment]
Could you point me to where this is mentioned? Maybe I do not quite get what you want. Give me a concrete example.

**Comment by tilmans** [comment]
I'm looking at the source (jar) of DiffRowGenerator class and I see this (note the **ignoreBlankLines = true** ):

    * These values are: showInlineDiffs = false; ignoreWhiteSpaces = true; ignoreBlankLines = true; ...
    *
    * For instantiating the DiffRowGenerator you should use the its builder. Like in example  <code>
    *    DiffRowGenerator generator = new DiffRowGenerator.Builder().showInlineDiffs(true).
    *      ignoreWhiteSpaces(true).columnWidth(100).build();
    * </code>
    */
    public final class DiffRowGenerator { ...

What I wanted to do was:

    DiffRowGenerator.create().ignoreBlankLines().build();

But neither the method nor the member variable exist. It seems like the documentation of the class is outdated?

**Comment by wumpz** [comment]
Aha. Now I see. So you want at both sides blank lines to be removed.

**Comment by tilmans** [comment]
Yes, the main use case is when generating a diff with:

    DiffRowGenerator generator = DiffRowGenerator.create()
                .mergeOriginalRevised(true)
                .newTag(f -> "**")     //introduce markdown style for bold
                .build();

If the input has multiple new lines with blank lines between them then you get something like:

    **A new text line**
    ****
    **Another new line**

It would be nicer if the output looked like this:

    **A new text line**
    
    **Another new line**

or

    **A new text line**
    **Another new line**

It's not a big issue but I was wondering why the option to remove blank lines is in the comments but not the code.

**Comment by wumpz** [comment]
How do you call the DiffRowGenerator? Could you give original and new as an example.

**Comment by wumpz** [comment]
By the way this ignore whitespaces is not for the output, but how the input is tokenized to generate the diff.

**Comment by wumpz** [comment]
With the fix of #66 this is solved as well. You will get your second wish 

    **A new text line**
    
    **Another new line**

However, now the blank line removal should be trivial.
