### ISSUE TITLE
DiffRowGenerator returns too many diffs in special cases

### ISSUE THREAD

**Issue by JaPaBu** [java-diff-utils/java-diff-utils#65]
**Describe the bug**
DiffRowGenerator returns too many diffs in special cases.

**To Reproduce**

```
 DiffRowGenerator generator = DiffRowGenerator.create()
                .showInlineDiffs(true)
                .reportLinesUnchanged(true)
                .oldTag(f -> "~")
                .newTag(f -> "**")
                .mergeOriginalRevised(true)
//                .inlineDiffByWord(true)
                .build();

        List<DiffRow> diffRows = generator.generateDiffRows(sortedRemovals, sortedAdditions);
```

sortedRemovals: 
["Ich möchte nicht mit einem Bot sprechen.", "Ich soll das schon wieder wiederholen?"]

sortedAdditions: 
["Ich möchte nicht mehr mit dir sprechen. Leite mich weiter.", "Kannst du mich zum Kundendienst weiterleiten?"]

**Expected behavior**
diffRows should have size 2 but it has size 3.

**System**
 - Java version 1.8
 - Version 4.5

Setting inlineDiffByWord(true) does not produce the error.

**Comment by wumpz** [comment]
You are diffing sortedRemovals and sortedAdditons? How do you know, that there should be 2 diffs?

**Comment by JaPaBu** [comment]
Well it should diff the 2 pairs hence it should return 2 DiffRows but it returns 3 instead :/

**Comment by wumpz** [comment]
Sorry missread diffrows as diffs. You are right, that the rowcount should be the same, but there could be multiple diff in one line. That was my fault.

However now I can reproduce your problem.

**Comment by wumpz** [comment]
After digging into this I find it I am not yet quit sure how to solve this. The diff result is correct. The problem is, that something without linefeed is replaced by something with linefeed and the linefeed that remains is replaced by another delta.

**Comment by wumpz** [comment]
So here is the first try to at least optionally try to fix this. 

There is a new method in the builder (**replaceOriginalLinefeedInChangesWithSpaces**) to switch this on. 
As you already found out, this happens only occasionally in this case I already mentioned.
