### ISSUE TITLE
Ignore Whitespaces Only Partially Works

### ISSUE THREAD

**Issue by zoaked** [java-diff-utils/java-diff-utils#66]
**Preface**
I'm not sure if this is a bug or if I am misusing the tool and/or not configuring it correctly.  If so, please consider this to be a question and I would appreciate any information that could be provided.

Thanks!

**Describe the bug**
When checking for equality, whitespaces are correctly ignored.  When generating differences, some whitespaces are still compared while others are deleted from the result.

**To Reproduce**
```//create a configured DiffRowGenerator
DiffRowGenerator generator = DiffRowGenerator.create()
		.showInlineDiffs(true)
		.inlineDiffByWord(true) 
		.ignoreWhiteSpaces(true)
		.oldTag(f -> "~")      //introduce markdown style for strikethrough
		.newTag(f -> "**")     //introduce markdown style for bold
		.build();

//compute the differences for two test texts.
List<DiffRow> rows1 = generator.generateDiffRows(
		Arrays.asList("This\nis\na\ntest."),
		Arrays.asList("This is a test"));
```
or a more basic example using tabs instead of newlines...
```
//compute the differences for two test texts.
List<DiffRow> rows2 = generator.generateDiffRows(
		Arrays.asList("This\tis\ta\ttest."),
		Arrays.asList("This is a test"));

```
or an even more basic example that just changes the number of spaces...
```
//compute the differences for two test texts.
List<DiffRow> rows3 = generator.generateDiffRows(
		Arrays.asList("This  is  a  test."),
		Arrays.asList("This is a test"));
```

**Actual Result**
 - rows1:
(period is correctly identified as an "old" tag while newlines are gone)
<pre>`Thisisatest~.~`</pre>
(spaces are considered to be "new" tags when we were asking for them to be ignored)
<pre>`This** **is** **a** **test`</pre>
 - rows2:
(period is correctly identified as an "old" tag while tabs are also treated as "old" tags)
<pre>`This~    ~is~    ~a~    ~test~.~`</pre>
(spaces are considered to be "new" tags when we are asking for them to be ignored)
<pre>`This** **is** **a** **test`</pre>
 - rows3:
(period is correctly identified as an "old" tag while the spaces are also treated as "old" tags)
<pre>`This~  ~is~  ~a~  ~test~.~`</pre>
(spaces are considered to be "new" tags when we are asking for them to be ignored)
<pre>`This** **is** **a** **test`</pre>

**Expected Behavior**
 - rows1:
<pre>This\nis\na\ntest~.~</pre>
<pre>This is a test</pre>
 - rows2:
<pre>This\tis\ta\ttest~.~</pre>
<pre>This is a test</pre>
 - rows3:
<pre>This  is  a  test~.~</pre>
<pre>This is a test</pre>

**Notes**
If a period is left at the end of the second string being diff-ed in any of the above blocks, this does not happen and the entire block is identified as matching like was expected.

**Suggested Fix**
1. Pass `DiffRowGenerator.equalizer` down to `DiffUtils.diff` when [DiffRowGenerator.generateInlineDiffs](https://github.com/java-diff-utils/java-diff-utils/blob/master/java-diff-utils/src/main/java/com/github/difflib/text/DiffRowGenerator.java#L293) is called.
1. Use an internal identifier for [merging](https://github.com/java-diff-utils/java-diff-utils/blob/master/java-diff-utils/src/main/java/com/github/difflib/text/DiffRowGenerator.java#L287-L288)/[splitting ](https://github.com/java-diff-utils/java-diff-utils/blob/master/java-diff-utils/src/main/java/com/github/difflib/text/DiffRowGenerator.java#L339-L340) instead of something that could be contained within the comparison.

**System**
 - Java version: 8 (1.8.0_151)
 - Diff Utils Version: 4.5

**Comment by wumpz** [comment]
Sorry it took a while. 

Could you check the latest version. 

You first example is not valid in this sense, because new lines are always new lines. You found indeed a bug. The ignore whitespace flag was not used for inline diffs.
