### ISSUE TITLE
Add docs explaining difference with diff-match-patch

### ISSUE THREAD

**Issue by jvican** [java-diff-utils/java-diff-utils#68]
**Describe the bug**
I'd like to know what are the differences between java-diff-utils and [diff-match-patch](https://github.com/google/diff-match-patch), especially when it comes to performance. Is there a concrete reason why this library was created instead of reusing the former?

**Expected behavior**
There some docs in the wiki explaining the rationale behind creating this library and how it compares with diff-match-patch.

**Comment by wumpz** [comment]
To be honest, I was not aware of this project. This was derived from the known java-diff-utils from Google.
