### ISSUE TITLE
AbstractDelta vs Delta in example

### ISSUE THREAD

**Issue by goretkin** [java-diff-utils/java-diff-utils#71]
The example at https://github.com/java-diff-utils/java-diff-utils/wiki/Examples

```java
//simple output the computed patch to console
for (Delta<String> delta : patch.getDeltas()) {
    System.out.println(delta);
}
```

seems to require `AbstractDelta<String>` in place of `Delta<String>`.

**Comment by wumpz** [comment]
Thx. Missed this example while refactoring.
