### ISSUE TITLE
Publish Javadoc

### ISSUE THREAD

**Issue by cowwoc** [java-diff-utils/java-diff-utils#72]
Can you please publish the Javadoc to Github to make the library easier to explore?

**Comment by wumpz** [comment]
I never did this for my projects. How to achieve this in a maven build. Javadocs are published along with the jar to maven central at the moment.

**Comment by cowwoc** [comment]
What I typically do is:

1. `mvn release:prepare`, `mvn release:perform`.
2. Then publish the contents of `target/apidocs` into the `hg_pages` branch of github, under `{version}/docs/api`.
3. Then link from README.md to `https://github.com/java-diff-utils/{version}/docs/api` and users can read the Javadoc directly from Github.

**Comment by wumpz** [comment]
I copied all into the gh-pages branch, but could not reference the site like you described. Is there a step missing?

**Comment by cowwoc** [comment]
@wumpz No, that's perfect. You ended up referencing the site as I expected.

FYI, you can compare against my own project over at https://github.com/cowwoc/requirements.java

I reference the Javadoc up-top, but the way you did it in the middle of README.md is fine too.

**Comment by wumpz** [comment]
I had to switch my documentation branch from master to gh-pages. That was the problem.

**Comment by cowwoc** [comment]
@wumpz Yes, that is unfortunately normal. It is a manual process for me too. One day I will automate it :)
