### ISSUE TITLE
Post-processing cleanup

### ISSUE THREAD

**Issue by cowwoc** [java-diff-utils/java-diff-utils#73]
https://neil.fraser.name/writing/diff/ section 3 mentions post-processing cleanup that https://github.com/google/diff-match-patch applies to the output. Does your library provide something similar?

**Comment by wumpz** [comment]
No. I post processing in this form is not done. However the diffs mentioned in Frasers paper are doing a letter wise diff. To achieve a "better looking" diff java-diff-utils are able to do a word like diff, it replaces words not letters.

**Comment by wumpz** [comment]
Look for instance at: https://github.com/java-diff-utils/java-diff-utils/wiki/Examples#multi-liner.

**Comment by cowwoc** [comment]
@wumpz How can https://github.com/java-diff-utils/java-diff-utils/blob/master/java-diff-utils/src/main/java/com/github/difflib/text/DiffRowGenerator.java#L361 ever work? Doesn't this method always return `Tag.CHANGE` for all rows?

**Comment by cowwoc** [comment]
@wumpz I'd like to do word-diffs but don't want to surround `newTag`/`oldTag` with anything. Can you please add a way to disable this functionality? Ideally `wrapInTag` should exit immediately instead of iterating through the sequence, but even if I configure `newTag` to a function that returns an empty string, I will end up with empty string elements before/after each tag which is not what I want.

**Comment by wumpz** [comment]
Could you give me an example? I don't get how this should look like.

**Comment by cowwoc** [comment]
@wumpz Essentially, I want to diff two strings and get back a `List<AbstractDelta>` with word-level granularity. I don't need any tag wrappers because `AbstractDelta.getType()` already tells me which text was added and removed.

**Comment by wumpz** [comment]
Understood. I will integrate that. 

Cheers

**Comment by cowwoc** [comment]
@wumpz in the end, I won't need this functionality. I ended up implementing my own hybrid between a word level and character level diff. It cannot be implemented in terms of `DiffRowGenerator`.

**Comment by wumpz** [comment]
Ok. Then I will close this issue.
