### ISSUE TITLE
Provide a mechanism to create a new delta from an existing delta without caring about its type

### ISSUE THREAD

**Issue by cowwoc** [java-diff-utils/java-diff-utils#75]
I am writing a method that needs to break a delta into pieces (e.g. two deltas that result in the same patch as the original delta). The current design is problematic because:

1. I don't want my method to know/care what the delta type is.
2. The `AbstractDelta` class is abstract, so I cannot simply invoke its constructor.
3. The `AbstractDelta` subtypes do not provide `with()` methods.
4. Some of your code (e.g. `DiffRowGenerator`) check the class type instance (e.g. `if (delta instanceof InsertDelta)` instead of using `AbstractDelta.getType()` so I cannot subclass `AbstractDelta` myself.

Probably the easiest way to resolve this is to add an abstract `withChunks(Chunk<T> original, Chunk<T> revised)` method to `AbstractDelta`.

**Comment by wumpz** [comment]
I agree, that different implementations of Deltas could be useful. I will replace all instance checks with getType checks.

**Comment by wumpz** [comment]
So I replaced all `instanceof `checks with its corresponding getType checks.

I not happy with an `withChunks `method. A delta in itself should be final. Do you need the specific apply / restore functionality with your new Delta? If not and with this `getType `change you could simply build your own DeltaClass that could hold all data with its corresponding type.

**Comment by cowwoc** [comment]
@wumpz I think you misunderstood what I meant by `withChunks`. The delta is final as you said. Invoking `withChunks` returns an new delta having the same type of the original, but having different source, target chunks. Are you okay with that?

**Comment by cowwoc** [comment]
@wumpz Great! Let me know when the SNAPSHOT is ready for testing.

**Comment by cowwoc** [comment]
@wumpz I just noticed the SNAPSHOT has been updated. I tested this new feature and it works great. Thank you! Looking forward to an official (non-SNAPSHOT) release.

**Comment by wumpz** [comment]
The release Issue is already there (#78).
