### ISSUE TITLE
Version changed from snapshot to snapshot without a release version being published

### ISSUE THREAD

**Issue by zoaked** [java-diff-utils/java-diff-utils#77]
**Describe the observation**
About a month ago, a commit was made that changed the pom version from 4.6-SNAPSHOT to 4.7-SNAPSHOT, but it appears that 4.6 (non-snapshot) was never commited or published to maven central.

**To Reproduce**
See 89c9f94aefe2a992278470617ac2be39211cf9d5

**Expected behavior**
I would like to request that the latest version of master be published to maven central so all of the excellent work you've put into the last 20 commits (and counting) can be utilized.

Thank you!

**Comment by wumpz** [comment]
To be honest, I don't know why this happened. However, a new release is near. I am still on #42.

**Comment by cowwoc** [comment]
@wumpz In theory, you could manually set the version number back to `4.6-SNAPSHOT` prior to making a release and there wouldn't be a hole.

**Comment by wumpz** [comment]
@cowwoc I know but since I already deployed 4.7-SNAPSHOT versions the next release should be 4.7.

**Comment by wumpz** [comment]
version 4.7 has been released

**Comment by cowwoc** [comment]
Great! Thank you very much.
