### ISSUE TITLE
issues when parsing git diff

### ISSUE THREAD

**Issue by luyijingxiu** [java-diff-utils/java-diff-utils#79]
**Describe the bug**
1. When parsing git diff like this 
``` diff
diff --git a/test/Issue.java b/test/Issue.java
new file mode 100644
index 00000000..9702606e
```
UnifiedDiffReader will throw UnifiedDiffParserException: "expected file start line not found"
I have analyze the code and found that `new file mode 100644` can't not be recognized. But I found regex that can recognized this line in comment of method `UnifiedDiffReader#parse()` 
   ```
 // schema = [[/^\s+/, normal], [/^diff\s/, start], [**/^new file mode \d+$/**, new_file], 
```
It seems that you intend not to recognize this, Could you please tell the reason?

2. The java.util.logging.Logger in UnifiedDiffReader is kind of chatty, How should I turn it off.

3. Is `UnifiedDiffUtils.parseUnifiedDiff()`  designed to only parse the first patch?

**Comment by wumpz** [comment]
You now this new implementation of UnifiedDiffReader was some kind of feature driven. So what was needed was implemented. 

This is simply missing. So I will look into it. By the way, pull requests are welcome.

**Comment by wumpz** [comment]
UnifiedDiffUtils is the **old** implementation, that only read the first patch.

**Comment by wumpz** [comment]
I will change the logger.

**Comment by luyijingxiu** [comment]
thank you for your reply, Actually, I only need to know lines that was added by parsing the diff file. I have modified your code to fit my need. I will commit a PR when possible.
