### ISSUE TITLE
Missing some changed lines when using UnifiedDiffReader.parseUnifiedDiff

### ISSUE THREAD

**Issue by HuGanghui** [java-diff-utils/java-diff-utils#83]
**Describe the bug**

Missing some changed lines when using UnifiedDiffReader.parseUnifiedDiff

**To Reproduce**
1. Example data
2. simple programm snippet
3. See error

https://github.com/java-diff-utils/java-diff-utils/blob/a8e4ce2eff297c7700a6215bacb548e30151b948/java-diff-utils/src/test/java/com/github/difflib/unifieddiff/UnifiedDiffReaderTest.java#L145-L159

when debug this test, I found that patch of file f2 is empty, but in line 11 of problem_diff_issue51.diff is a changed line, right? 

And the `file1.getFromFile()).isEqualTo("f1");` should be `old/f1` right? same as `new/f1`, `old/f2`, `new/f2` in the diff file.

https://github.com/java-diff-utils/java-diff-utils/blob/a8e4ce2eff297c7700a6215bacb548e30151b948/java-diff-utils/src/test/resources/com/github/difflib/unifieddiff/problem_diff_issue51.diff#L7-L11

<img width="818" alt="image" src="https://user-images.githubusercontent.com/50866227/84558641-f95b4880-ad66-11ea-8ab9-6e927e8a1eba.png">
 
**Expected behavior**

**System**
 - Java version 1.8
 - Version 
```xml
<groupId>io.github.java-diff-utils</groupId>
<artifactId>java-diff-utils</artifactId>
<version>4.5</version>
```

**Comment by wumpz** [comment]
In fact the test diff file was syntactically not correct. Now I checked both files diffs.
