### ISSUE TITLE
JGit version

### ISSUE THREAD

**Issue by I-Vargas** [java-diff-utils/java-diff-utils#92]
Having clashing problems with the JGit version.

Is there a reason to keep using 4.4.1 from 2016, instead of updating to 5.8?

**Comment by wumpz** [comment]
I don't think so. Just laziness I guess. I will look into this.

**Comment by I-Vargas** [comment]
you could look into adding a bot to check outdated dependencies, like dependabot or renovatebot.

**Comment by wumpz** [comment]
last commit integrates jgit 5.8.1
