### ISSUE TITLE
Request: New release containing fix for #83

### ISSUE THREAD

**Issue by tomasbjerre** [java-diff-utils/java-diff-utils#97]
I stumbled upon #83 when trying to use this library to fix https://github.com/tomasbjerre/violations-lib/issues/95.

I need this fix: https://github.com/java-diff-utils/java-diff-utils/commit/dbe601c2fcb766dda91b33d1a4db15dc8a056959

Would be nice if you can make a release with this included.

**Comment by wumpz** [comment]
just released
